// Curated player roster. Active-player career stats verified against ATP/WTA
// tour sites and Wikipedia in May 2026 — refresh after any major tournament.
// Retired-player stats are final ledgers. Speed/RPM figures are typical-match
// values, not historical maximums, unless noted.
import type { Player } from './libPlayers';

export const players: Player[] = [
  {
    slug: 'roger-federer',
    fullName: 'Roger Federer',
    shortName: 'Federer',
    tour: 'ATP',
    bornIso: '1981-08-08',
    birthplace: 'Basel, Switzerland',
    heightCm: 185,
    handedness: 'right',
    backhandStyle: 'one-handed',
    era: ['modern', 'current'],
    styleOfPlay: ['all-court', 'attacking baseliner', 'transition artist'],
    surfaceStrengths: ['grass', 'hard', 'clay'],
    shotPalette: {
      serveSpeedKmh: 200,
      forehandSpeedKmh: 130,
      forehandRpm: 2700,
      signatureShots: ['inside-out forehand', 'kick serve', 'sliced one-handed backhand', 'SABR (Sneak Attack By Roger)'],
      weakness: 'high backhand on slow surfaces',
    },
    career: {
      grandSlams: 20,
      weeksAtNumberOne: 310,
      yearEndNumberOne: 5,
      careerHighRanking: 1,
      turnedPro: 1998,
      retiredYear: 2022,
    },
    bio: "The aesthete's player. Federer's tennis was an argument that beauty and effectiveness need not be opposed — a forehand whipped from anywhere on the court, a kick serve no one could read, footwork that made him appear unhurried even in extremity. Twenty Slams, five year-end #1s, and the longest reign of cultural reverence the sport has known.",
    signatureMatch: 'Wimbledon 2008 Final vs Nadal',
    rivalries: ['rafael-nadal', 'novak-djokovic'],
    status: 'retired',
    dataConfidence: 'verified',
    titles: [
      { year: 2001, tournament: 'Milan', city: 'Milan', surface: 'carpet', tier: 'atp-250', opponent: 'Julien Boutter', score: '6-4 6-7(7) 6-4' },
      { year: 2002, tournament: 'Sydney', city: 'Sydney', surface: 'hard', tier: 'atp-250', opponent: 'Juan Ignacio Chela', score: '6-3 6-3' },
      { year: 2002, tournament: 'Hamburg', city: 'Hamburg', surface: 'clay', tier: 'masters-1000', opponent: 'Marat Safin', score: '6-1 6-3 6-4' },
      { year: 2002, tournament: 'Vienna', city: 'Vienna', surface: 'hard', tier: 'atp-250', opponent: 'Jiri Novak', score: '6-4 6-1 3-6 6-4' },
      { year: 2003, tournament: 'Marseille', city: 'Marseille', surface: 'hard', tier: 'atp-250', opponent: 'Jonas Bjorkman', score: '6-2 7-6(6)' },
      { year: 2003, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Jiri Novak', score: '6-1 7-6(2)' },
      { year: 2003, tournament: 'Munich', city: 'Munich', surface: 'clay', tier: 'atp-250', opponent: 'Jarkko Nieminen', score: '6-1 6-4' },
      { year: 2003, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-250', opponent: 'Nicolas Kiefer', score: '6-1 6-3' },
      { year: 2003, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Mark Philippoussis', score: '7-6(5) 6-2 7-6(3)' },
      { year: 2003, tournament: 'Gstaad', city: 'Gstaad', surface: 'clay', tier: 'atp-250', opponent: 'Radek Stepanek', score: '5-7 6-3 6-3 1-6 6-3' },
      { year: 2003, tournament: 'Vienna', city: 'Vienna', surface: 'hard', tier: 'atp-250', opponent: 'Carlos Moya', score: '6-3 6-3 6-3' },
      { year: 2003, tournament: 'ATP Finals', city: 'Houston', surface: 'hard', tier: 'atp-finals', opponent: 'Andre Agassi', score: '6-3 6-0 6-4' },
      { year: 2004, tournament: 'Australian Open', city: 'Melbourne', surface: 'hard', tier: 'grand-slam', opponent: 'Marat Safin', score: '7-6(3) 6-4 6-2' },
      { year: 2004, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Feliciano Lopez', score: '4-6 6-1 6-2' },
      { year: 2004, tournament: 'Indian Wells', city: 'Indian Wells', surface: 'hard', tier: 'masters-1000', opponent: 'Tim Henman', score: '6-3 6-3' },
      { year: 2004, tournament: 'Hamburg', city: 'Hamburg', surface: 'clay', tier: 'masters-1000', opponent: 'Guillermo Coria', score: '4-6 6-4 6-2 6-3' },
      { year: 2004, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-250', opponent: 'Mardy Fish', score: '6-0 6-3' },
      { year: 2004, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Andy Roddick', score: '4-6 7-5 7-6(3) 6-4' },
      { year: 2004, tournament: 'Gstaad', city: 'Gstaad', surface: 'clay', tier: 'atp-250', opponent: 'Igor Andreev', score: '6-2 6-3 5-7 6-3' },
      { year: 2004, tournament: 'Toronto', city: 'Toronto', surface: 'hard', tier: 'masters-1000', opponent: 'Andy Roddick', score: '7-5 6-3' },
      { year: 2004, tournament: 'US Open', city: 'New York', surface: 'hard', tier: 'grand-slam', opponent: 'Lleyton Hewitt', score: '6-0 7-6(3) 6-0' },
      { year: 2004, tournament: 'Bangkok', city: 'Bangkok', surface: 'hard', tier: 'atp-250', opponent: 'Andy Roddick', score: '6-4 6-0' },
      { year: 2004, tournament: 'ATP Finals', city: 'Houston', surface: 'hard', tier: 'atp-finals', opponent: 'Lleyton Hewitt', score: '6-3 6-2' },
      { year: 2005, tournament: 'Doha', city: 'Doha', surface: 'hard', tier: 'atp-250', opponent: 'Ivan Ljubicic', score: '6-3 6-1' },
      { year: 2005, tournament: 'Rotterdam', city: 'Rotterdam', surface: 'hard', tier: 'atp-500', opponent: 'Ivan Ljubicic', score: '5-7 7-5 7-6(7)' },
      { year: 2005, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Ivan Ljubicic', score: '6-1 6-7(6) 6-3' },
      { year: 2005, tournament: 'Indian Wells', city: 'Indian Wells', surface: 'hard', tier: 'masters-1000', opponent: 'Lleyton Hewitt', score: '6-2 6-4 6-4' },
      { year: 2005, tournament: 'Miami', city: 'Miami', surface: 'hard', tier: 'masters-1000', opponent: 'Rafael Nadal', score: '2-6 6-7(4) 7-6(5) 6-3 6-1' },
      { year: 2005, tournament: 'Hamburg', city: 'Hamburg', surface: 'clay', tier: 'masters-1000', opponent: 'Richard Gasquet', score: '6-3 7-5 7-6(4)' },
      { year: 2005, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-250', opponent: 'Marat Safin', score: '6-4 6-7(6) 6-4' },
      { year: 2005, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Andy Roddick', score: '6-2 7-6(2) 6-4' },
      { year: 2005, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'Andy Roddick', score: '6-3 7-5' },
      { year: 2005, tournament: 'US Open', city: 'New York', surface: 'hard', tier: 'grand-slam', opponent: 'Andre Agassi', score: '6-3 2-6 7-6(1) 6-1' },
      { year: 2005, tournament: 'Bangkok', city: 'Bangkok', surface: 'hard', tier: 'atp-250', opponent: 'Andy Murray', score: '6-3 7-5' },
      { year: 2006, tournament: 'Doha', city: 'Doha', surface: 'hard', tier: 'atp-250', opponent: 'Gael Monfils', score: '6-3 7-6(5)' },
      { year: 2006, tournament: 'Australian Open', city: 'Melbourne', surface: 'hard', tier: 'grand-slam', opponent: 'Marcos Baghdatis', score: '5-7 7-5 6-0 6-2' },
      { year: 2006, tournament: 'Indian Wells', city: 'Indian Wells', surface: 'hard', tier: 'masters-1000', opponent: 'James Blake', score: '7-5 6-3 6-0' },
      { year: 2006, tournament: 'Miami', city: 'Miami', surface: 'hard', tier: 'masters-1000', opponent: 'Ivan Ljubicic', score: '7-6(5) 7-6(4) 7-6(6)' },
      { year: 2006, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-250', opponent: 'Tomas Berdych', score: '6-0 6-7(4) 6-2' },
      { year: 2006, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Rafael Nadal', score: '6-0 7-6(5) 6-7(2) 6-3' },
      { year: 2006, tournament: 'Toronto', city: 'Toronto', surface: 'hard', tier: 'masters-1000', opponent: 'Richard Gasquet', score: '2-6 6-3 6-2' },
      { year: 2006, tournament: 'US Open', city: 'New York', surface: 'hard', tier: 'grand-slam', opponent: 'Andy Roddick', score: '6-2 4-6 7-5 6-1' },
      { year: 2006, tournament: 'Tokyo', city: 'Tokyo', surface: 'hard', tier: 'atp-500', opponent: 'Tim Henman', score: '6-3 6-3' },
      { year: 2006, tournament: 'Madrid', city: 'Madrid', surface: 'hard', tier: 'masters-1000', opponent: 'Fernando Gonzalez', score: '7-5 6-1 6-0' },
      { year: 2006, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-250', opponent: 'Fernando Gonzalez', score: '6-3 6-2 7-6(3)' },
      { year: 2006, tournament: 'ATP Finals', city: 'Shanghai', surface: 'hard', tier: 'atp-finals', opponent: 'James Blake', score: '6-0 6-3 6-4' },
      { year: 2007, tournament: 'Australian Open', city: 'Melbourne', surface: 'hard', tier: 'grand-slam', opponent: 'Fernando Gonzalez', score: '7-6(2) 6-4 6-4' },
      { year: 2007, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Mikhail Youzhny', score: '6-4 6-3' },
      { year: 2007, tournament: 'Hamburg', city: 'Hamburg', surface: 'clay', tier: 'masters-1000', opponent: 'Rafael Nadal', score: '2-6 6-2 6-0' },
      { year: 2007, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Rafael Nadal', score: '7-6(7) 4-6 7-6(3) 2-6 6-2' },
      { year: 2007, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'James Blake', score: '6-1 6-4' },
      { year: 2007, tournament: 'US Open', city: 'New York', surface: 'hard', tier: 'grand-slam', opponent: 'Novak Djokovic', score: '7-6(4) 7-6(2) 6-4' },
      { year: 2007, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-250', opponent: 'Jarkko Nieminen', score: '6-3 6-4' },
      { year: 2007, tournament: 'ATP Finals', city: 'Shanghai', surface: 'hard', tier: 'atp-finals', opponent: 'David Ferrer', score: '6-2 6-3 6-2' },
      { year: 2008, tournament: 'Estoril', city: 'Estoril', surface: 'clay', tier: 'atp-250', opponent: 'Nikolay Davydenko', score: '7-6(5) 1-2 ret.' },
      { year: 2008, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-250', opponent: 'Philipp Kohlschreiber', score: '6-3 6-4' },
      { year: 2008, tournament: 'US Open', city: 'New York', surface: 'hard', tier: 'grand-slam', opponent: 'Andy Murray', score: '6-2 7-5 6-2' },
      { year: 2008, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-250', opponent: 'David Nalbandian', score: '6-3 6-4' },
      { year: 2009, tournament: 'Madrid', city: 'Madrid', surface: 'clay', tier: 'masters-1000', opponent: 'Rafael Nadal', score: '6-4 6-4' },
      { year: 2009, tournament: 'French Open', city: 'Paris', surface: 'clay', tier: 'grand-slam', opponent: 'Robin Soderling', score: '6-1 7-6(1) 6-4' },
      { year: 2009, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Andy Roddick', score: '5-7 7-6(6) 7-6(5) 3-6 16-14' },
      { year: 2009, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'Novak Djokovic', score: '6-1 7-5' },
      { year: 2009, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Novak Djokovic', score: '6-3 6-4' },
      { year: 2010, tournament: 'Australian Open', city: 'Melbourne', surface: 'hard', tier: 'grand-slam', opponent: 'Andy Murray', score: '6-3 6-4 7-6(11)' },
      { year: 2010, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'Mardy Fish', score: '6-7(5) 7-6(1) 6-4' },
      { year: 2010, tournament: 'Stockholm', city: 'Stockholm', surface: 'hard', tier: 'atp-250', opponent: 'Florian Mayer', score: '6-4 6-3' },
      { year: 2010, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Novak Djokovic', score: '6-4 3-6 6-1' },
      { year: 2010, tournament: 'ATP Finals', city: 'London', surface: 'hard', tier: 'atp-finals', opponent: 'Rafael Nadal', score: '6-3 3-6 6-1' },
      { year: 2011, tournament: 'Doha', city: 'Doha', surface: 'hard', tier: 'atp-250', opponent: 'Nikolay Davydenko', score: '6-3 6-4' },
      { year: 2011, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Kei Nishikori', score: '6-1 6-3' },
      { year: 2011, tournament: 'Paris', city: 'Paris', surface: 'hard', tier: 'masters-1000', opponent: 'Jo-Wilfried Tsonga', score: '6-1 7-6(3)' },
      { year: 2011, tournament: 'ATP Finals', city: 'London', surface: 'hard', tier: 'atp-finals', opponent: 'Jo-Wilfried Tsonga', score: '6-3 6-7(6) 6-3' },
      { year: 2012, tournament: 'Rotterdam', city: 'Rotterdam', surface: 'hard', tier: 'atp-500', opponent: 'Juan Martin del Potro', score: '6-1 6-4' },
      { year: 2012, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Andy Murray', score: '7-5 6-4' },
      { year: 2012, tournament: 'Indian Wells', city: 'Indian Wells', surface: 'hard', tier: 'masters-1000', opponent: 'John Isner', score: '7-6(7) 6-3' },
      { year: 2012, tournament: 'Madrid', city: 'Madrid', surface: 'clay', tier: 'masters-1000', opponent: 'Tomas Berdych', score: '3-6 7-5 7-5' },
      { year: 2012, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Andy Murray', score: '4-6 7-5 6-3 6-4' },
      { year: 2012, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'Novak Djokovic', score: '6-0 7-6(7)' },
      { year: 2012, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Juan Martin del Potro', score: '6-4 6-7(4) 7-6(3)' },
      { year: 2013, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-500', opponent: 'Mikhail Youzhny', score: '6-7(5) 6-3 6-4' },
      { year: 2014, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Tomas Berdych', score: '3-6 6-4 6-3' },
      { year: 2014, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-500', opponent: 'Alejandro Falla', score: '7-6(2) 7-6(3)' },
      { year: 2014, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'David Ferrer', score: '6-3 1-6 6-2' },
      { year: 2014, tournament: 'Shanghai', city: 'Shanghai', surface: 'hard', tier: 'masters-1000', opponent: 'Gilles Simon', score: '7-6(6) 7-6(2)' },
      { year: 2014, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'David Goffin', score: '6-2 6-2' },
      { year: 2015, tournament: 'Brisbane', city: 'Brisbane', surface: 'hard', tier: 'atp-250', opponent: 'Milos Raonic', score: '6-4 6-7(2) 6-4' },
      { year: 2015, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Novak Djokovic', score: '6-3 7-5' },
      { year: 2015, tournament: 'Istanbul', city: 'Istanbul', surface: 'clay', tier: 'atp-250', opponent: 'Pablo Cuevas', score: '6-3 7-6(11)' },
      { year: 2015, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-500', opponent: 'Andreas Seppi', score: '7-6(1) 6-4' },
      { year: 2015, tournament: 'Cincinnati', city: 'Cincinnati', surface: 'hard', tier: 'masters-1000', opponent: 'Novak Djokovic', score: '7-6(1) 6-3' },
      { year: 2015, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Rafael Nadal', score: '6-3 5-7 6-3' },
      { year: 2017, tournament: 'Australian Open', city: 'Melbourne', surface: 'hard', tier: 'grand-slam', opponent: 'Rafael Nadal', score: '6-4 3-6 6-1 3-6 6-3' },
      { year: 2017, tournament: 'Indian Wells', city: 'Indian Wells', surface: 'hard', tier: 'masters-1000', opponent: 'Stan Wawrinka', score: '6-4 7-5' },
      { year: 2017, tournament: 'Miami', city: 'Miami', surface: 'hard', tier: 'masters-1000', opponent: 'Rafael Nadal', score: '6-3 6-4' },
      { year: 2017, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-500', opponent: 'Alexander Zverev', score: '6-1 6-3' },
      { year: 2017, tournament: 'Wimbledon', city: 'London', surface: 'grass', tier: 'grand-slam', opponent: 'Marin Cilic', score: '6-3 6-1 6-4' },
      { year: 2017, tournament: 'Shanghai', city: 'Shanghai', surface: 'hard', tier: 'masters-1000', opponent: 'Rafael Nadal', score: '6-4 6-3' },
      { year: 2017, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Juan Martin del Potro', score: '6-7(5) 6-4 6-3' },
      { year: 2018, tournament: 'Australian Open', city: 'Melbourne', surface: 'hard', tier: 'grand-slam', opponent: 'Marin Cilic', score: '6-2 6-7(5) 6-3 3-6 6-1' },
      { year: 2018, tournament: 'Rotterdam', city: 'Rotterdam', surface: 'hard', tier: 'atp-500', opponent: 'Grigor Dimitrov', score: '6-2 6-2' },
      { year: 2018, tournament: 'Stuttgart', city: 'Stuttgart', surface: 'grass', tier: 'atp-250', opponent: 'Milos Raonic', score: '6-4 7-6(3)' },
      { year: 2018, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Marius Copil', score: '7-6(5) 6-4' },
      { year: 2019, tournament: 'Dubai', city: 'Dubai', surface: 'hard', tier: 'atp-500', opponent: 'Stefanos Tsitsipas', score: '6-4 6-4' },
      { year: 2019, tournament: 'Miami', city: 'Miami', surface: 'hard', tier: 'masters-1000', opponent: 'John Isner', score: '6-1 6-4' },
      { year: 2019, tournament: 'Halle', city: 'Halle', surface: 'grass', tier: 'atp-500', opponent: 'David Goffin', score: '7-6(2) 6-1' },
      { year: 2019, tournament: 'Basel', city: 'Basel', surface: 'hard', tier: 'atp-500', opponent: 'Alex de Minaur', score: '6-2 6-2' },
    ],
  },
  {
    slug: 'rafael-nadal',
    fullName: 'Rafael Nadal',
    shortName: 'Nadal',
    tour: 'ATP',
    bornIso: '1986-06-03',
    birthplace: 'Manacor, Mallorca, Spain',
    heightCm: 185,
    handedness: 'left',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['aggressive baseliner', 'topspin generator', 'physical fighter'],
    surfaceStrengths: ['clay', 'hard', 'grass'],
    shotPalette: {
      serveSpeedKmh: 195,
      forehandSpeedKmh: 130,
      forehandRpm: 3200,
      signatureShots: ['lasso forehand', 'banana shot', 'cross-court topspin forehand', 'inside-out forehand to backhand corner'],
      weakness: 'high backhand under pressure',
    },
    career: {
      grandSlams: 22,
      weeksAtNumberOne: 209,
      yearEndNumberOne: 5,
      careerHighRanking: 1,
      turnedPro: 2001,
      retiredYear: 2024,
    },
    bio: 'If Federer is light, Nadal is gravity. He turned topspin into a weapon and Roland Garros into a 14-Slam fiefdom. Left-handed, full-throated, relentless — Nadal redefined what physical and mental commitment looked like on a tennis court, and made every long rally feel like a referendum on willpower.',
    signatureMatch: 'Wimbledon 2008 Final vs Federer',
    rivalries: ['roger-federer', 'novak-djokovic'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'novak-djokovic',
    fullName: 'Novak Djokovic',
    shortName: 'Djokovic',
    tour: 'ATP',
    bornIso: '1987-05-22',
    birthplace: 'Belgrade, Serbia',
    heightCm: 188,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['counterpuncher', 'baseline', 'defense-into-offense'],
    surfaceStrengths: ['hard', 'grass', 'clay'],
    shotPalette: {
      serveSpeedKmh: 200,
      forehandSpeedKmh: 130,
      backhandSpeedKmh: 130,
      signatureShots: ['cross-court two-handed backhand', 'return of serve', 'down-the-line backhand', 'drop shot'],
      weakness: 'high-bouncing topspin to the forehand on slow clay',
    },
    career: {
      grandSlams: 24,
      weeksAtNumberOne: 428,
      yearEndNumberOne: 8,
      careerHighRanking: 1,
      turnedPro: 2003,
    },
    bio: 'The most complete defender ever to play, and the man who turned defense into offense in a single shot. Djokovic\'s flexibility, return of serve, and refusal to break under pressure built a 24-Slam case for him as the greatest of his era — perhaps any era.',
    signatureMatch: 'Wimbledon 2019 Final vs Federer',
    rivalries: ['roger-federer', 'rafael-nadal', 'andy-murray'],
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'jannik-sinner',
    fullName: 'Jannik Sinner',
    shortName: 'Sinner',
    tour: 'ATP',
    bornIso: '2001-08-16',
    birthplace: 'San Candido, Italy',
    heightCm: 188,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['flat-hitter', 'aggressive baseliner', 'court-craft'],
    surfaceStrengths: ['hard', 'clay', 'grass'],
    shotPalette: {
      serveSpeedKmh: 205,
      forehandSpeedKmh: 135,
      backhandSpeedKmh: 130,
      signatureShots: ['flat down-the-line backhand', 'inside-in forehand', 'first serve out wide on the deuce side'],
      weakness: 'occasional dip in second-serve points',
    },
    career: {
      grandSlams: 4,
      weeksAtNumberOne: 69,
      yearEndNumberOne: 1,
      careerHighRanking: 1,
      turnedPro: 2018,
    },
    bio: "Quiet feet and a quieter face — Sinner's tennis is precision tuned to a frequency the rest of the tour is still learning. Four majors (Australian Open '24 and '25, US Open '24, Wimbledon '25), the 2024 year-end #1, and a rivalry with Alcaraz that the next decade of men's tennis will be measured by.",
    rivalries: ['carlos-alcaraz'],
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'carlos-alcaraz',
    fullName: 'Carlos Alcaraz',
    shortName: 'Alcaraz',
    tour: 'ATP',
    bornIso: '2003-05-05',
    birthplace: 'El Palmar, Murcia, Spain',
    heightCm: 183,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['all-court', 'shotmaker', 'aggressive baseliner'],
    surfaceStrengths: ['clay', 'grass', 'hard'],
    shotPalette: {
      serveSpeedKmh: 200,
      forehandSpeedKmh: 140,
      forehandRpm: 3000,
      signatureShots: ['drop shot', 'running forehand pass', 'forehand winner from defense', 'serve-and-volley'],
      weakness: 'occasional decision-making under fatigue',
    },
    career: {
      grandSlams: 7,
      weeksAtNumberOne: 66,
      yearEndNumberOne: 2,
      careerHighRanking: 1,
      turnedPro: 2018,
    },
    bio: "The full inheritance. Alcaraz brings Federer's hands, Nadal's heart, and Djokovic's range into a single body — and at the 2026 Australian Open completed the Career Grand Slam to reach seven majors before his 23rd birthday. The ceiling stopped being a ceiling.",
    rivalries: ['jannik-sinner', 'novak-djokovic'],
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'pete-sampras',
    fullName: 'Pete Sampras',
    shortName: 'Sampras',
    tour: 'ATP',
    bornIso: '1971-08-12',
    birthplace: 'Washington, D.C., USA',
    heightCm: 185,
    handedness: 'right',
    backhandStyle: 'one-handed',
    era: ['modern'],
    styleOfPlay: ['serve-and-volley', 'all-court', 'attacking'],
    surfaceStrengths: ['grass', 'hard', 'carpet'],
    shotPalette: {
      serveSpeedKmh: 210,
      forehandSpeedKmh: 130,
      signatureShots: ['second-serve kicker', 'running forehand', 'slam-dunk smash', 'cross-court forehand volley'],
      weakness: 'extended baseline rallies on slow clay',
    },
    career: {
      grandSlams: 14,
      weeksAtNumberOne: 286,
      yearEndNumberOne: 6,
      careerHighRanking: 1,
      turnedPro: 1988,
      retiredYear: 2002,
    },
    bio: 'The serve was a guillotine, the running forehand a magic trick. Sampras owned the 90s with quiet, almost monastic focus — 14 Slams when 14 was the ceiling, a serve-and-volley game preserved like a final flame.',
    signatureMatch: 'US Open 1990 Final vs Agassi',
    rivalries: ['andre-agassi', 'jim-courier'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'john-mcenroe',
    fullName: 'John McEnroe',
    shortName: 'McEnroe',
    tour: 'ATP',
    bornIso: '1959-02-16',
    birthplace: 'Wiesbaden, West Germany (raised New York)',
    heightCm: 180,
    handedness: 'left',
    backhandStyle: 'one-handed',
    era: ['open-classic'],
    styleOfPlay: ['serve-and-volley', 'touch artist', 'attacking'],
    surfaceStrengths: ['grass', 'carpet', 'hard'],
    shotPalette: {
      serveSpeedKmh: 180,
      signatureShots: ['lefty slice serve out wide', 'half-volley', 'angled drop volley', 'sliced one-handed backhand'],
      weakness: 'high-bouncing topspin from the baseline',
    },
    career: {
      grandSlams: 7,
      weeksAtNumberOne: 170,
      yearEndNumberOne: 4,
      careerHighRanking: 1,
      turnedPro: 1978,
      retiredYear: 1992,
    },
    bio: "Touch and temper in equal measure. McEnroe's hands were softer than anyone's, his anger louder than anyone's, and his serve-and-volley game an art form that closed an era. Seven Slams, a left-handed serve that bent space, and a mind everyone wanted to know.",
    signatureMatch: 'Wimbledon 1980 Final vs Borg',
    rivalries: ['bjorn-borg', 'jimmy-connors', 'ivan-lendl'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'jim-courier',
    fullName: 'Jim Courier',
    shortName: 'Courier',
    tour: 'ATP',
    bornIso: '1970-08-17',
    birthplace: 'Sanford, Florida, USA',
    heightCm: 185,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['modern'],
    styleOfPlay: ['aggressive baseliner', 'flat-hitter', 'big forehand'],
    surfaceStrengths: ['clay', 'hard'],
    shotPalette: {
      serveSpeedKmh: 195,
      forehandSpeedKmh: 130,
      signatureShots: ['open-stance inside-out forehand', 'flat two-handed backhand', 'first-strike forehand from the middle'],
      weakness: 'low-bouncing surfaces and serve-and-volley pressure',
    },
    career: {
      grandSlams: 4,
      weeksAtNumberOne: 58,
      yearEndNumberOne: 1,
      careerHighRanking: 1,
      turnedPro: 1988,
      retiredYear: 2000,
    },
    bio: 'Buzzcut and bandana, two-fisted backhand, and an open-stance forehand that flattened the ball into the corner. Courier was the bridge between the wood-era touch artists and the power baseliners — four majors, time at #1, and underrated as both a player and now a Davis Cup mind.',
    rivalries: ['pete-sampras', 'andre-agassi'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'rod-laver',
    fullName: 'Rod Laver',
    shortName: 'Laver',
    tour: 'ATP',
    bornIso: '1938-08-09',
    birthplace: 'Rockhampton, Queensland, Australia',
    heightCm: 173,
    handedness: 'left',
    backhandStyle: 'one-handed',
    era: ['pre-open', 'open-classic'],
    styleOfPlay: ['all-court', 'serve-and-volley', 'wristy attacker'],
    surfaceStrengths: ['grass', 'clay', 'hard', 'carpet'],
    shotPalette: {
      signatureShots: ['lefty topspin forehand', 'sliced one-handed backhand', 'serve-and-volley to the body', 'lob volley'],
    },
    career: {
      grandSlams: 11,
      careerHighRanking: 1,
      turnedPro: 1962,
      retiredYear: 1979,
    },
    bio: 'The original. Two calendar Grand Slams (one as an amateur in 1962, one in the Open Era in 1969), a left-handed wrist that could carve any spin, and a foundational influence on everyone who came after. The only man to do it — twice.',
    rivalries: ['ken-rosewall'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'ivan-lendl',
    fullName: 'Ivan Lendl',
    shortName: 'Lendl',
    tour: 'ATP',
    bornIso: '1960-03-07',
    birthplace: 'Ostrava, Czechoslovakia',
    heightCm: 188,
    handedness: 'right',
    backhandStyle: 'one-handed',
    era: ['open-classic', 'modern'],
    styleOfPlay: ['power baseliner', 'fitness pioneer', 'big forehand'],
    surfaceStrengths: ['clay', 'hard', 'carpet'],
    shotPalette: {
      serveSpeedKmh: 195,
      forehandSpeedKmh: 130,
      signatureShots: ['inside-out forehand', 'kick second serve', 'topspin one-handed backhand', 'cross-court forehand passing shot'],
      weakness: 'grass-court footing and low slices',
    },
    career: {
      grandSlams: 8,
      weeksAtNumberOne: 270,
      yearEndNumberOne: 4,
      careerHighRanking: 1,
      turnedPro: 1978,
      retiredYear: 1994,
    },
    bio: 'The man who built the modern professional. Lendl trained, ate, and thought about tennis with a discipline the sport had never seen, and dragged the men\'s game into the 80s and 90s with him. Eight Slams, eight straight US Open finals, and a coaching second act that built Murray\'s majors.',
    rivalries: ['john-mcenroe', 'jimmy-connors', 'mats-wilander'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'andre-agassi',
    fullName: 'Andre Agassi',
    shortName: 'Agassi',
    tour: 'ATP',
    bornIso: '1970-04-29',
    birthplace: 'Las Vegas, Nevada, USA',
    heightCm: 180,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['modern', 'current'],
    styleOfPlay: ['aggressive baseliner', 'returner', 'clean ball-striker'],
    surfaceStrengths: ['hard', 'clay', 'grass'],
    shotPalette: {
      serveSpeedKmh: 200,
      forehandSpeedKmh: 130,
      signatureShots: ['return of serve', 'flat two-handed backhand down the line', 'inside-out forehand', 'short-ball forehand winner'],
      weakness: 'serve under pressure',
    },
    career: {
      grandSlams: 8,
      weeksAtNumberOne: 101,
      yearEndNumberOne: 1,
      careerHighRanking: 1,
      turnedPro: 1986,
      retiredYear: 2006,
    },
    bio: "From the rebel who refused Wimbledon's whites to the elder statesman who shaved his head and won majors into his 30s — Agassi's career was a study in reinvention. Eight majors, a career Slam, and the cleanest contact in the game.",
    signatureMatch: 'US Open 1990 Final vs Sampras',
    rivalries: ['pete-sampras', 'jim-courier'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'bjorn-borg',
    fullName: 'Björn Borg',
    shortName: 'Borg',
    tour: 'ATP',
    bornIso: '1956-06-06',
    birthplace: 'Södertälje, Sweden',
    heightCm: 180,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['open-classic'],
    styleOfPlay: ['baseline', 'topspin generator', 'ice-cold competitor'],
    surfaceStrengths: ['clay', 'grass'],
    shotPalette: {
      serveSpeedKmh: 180,
      signatureShots: ['heavy topspin forehand', 'two-handed backhand passing shot', 'kick serve', 'cross-court loop'],
    },
    career: {
      grandSlams: 11,
      weeksAtNumberOne: 109,
      yearEndNumberOne: 2,
      careerHighRanking: 1,
      turnedPro: 1973,
      retiredYear: 1983,
    },
    bio: 'The original cool. Borg won 11 Slams before he was 26 and then walked away, leaving a generation chasing the meaning of his absence. His topspin and his stillness were both ahead of their time.',
    signatureMatch: 'Wimbledon 1980 Final vs McEnroe',
    rivalries: ['john-mcenroe', 'jimmy-connors'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'jimmy-connors',
    fullName: 'Jimmy Connors',
    shortName: 'Connors',
    tour: 'ATP',
    bornIso: '1952-09-02',
    birthplace: 'East St. Louis, Illinois, USA',
    heightCm: 178,
    handedness: 'left',
    backhandStyle: 'two-handed',
    era: ['open-classic'],
    styleOfPlay: ['flat-hitter', 'aggressive returner', 'fighter'],
    surfaceStrengths: ['hard', 'grass', 'carpet', 'clay'],
    shotPalette: {
      signatureShots: ['flat two-handed backhand', 'cross-court forehand return', 'wide lefty serve', 'down-the-line backhand pass'],
    },
    career: {
      grandSlams: 8,
      weeksAtNumberOne: 268,
      yearEndNumberOne: 5,
      careerHighRanking: 1,
      turnedPro: 1972,
      retiredYear: 1996,
    },
    bio: 'Two-handed backhand, lefty shotgun forehand, and a refusal to lose. Connors won 109 ATP titles, eight majors, and at 39 years old made one last US Open semifinal that no one watching has ever forgotten.',
    signatureMatch: 'US Open 1991 Quarterfinal vs Krickstein',
    rivalries: ['bjorn-borg', 'john-mcenroe', 'ivan-lendl'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'andy-roddick',
    fullName: 'Andy Roddick',
    shortName: 'Roddick',
    tour: 'ATP',
    bornIso: '1982-08-30',
    birthplace: 'Omaha, Nebraska, USA',
    heightCm: 188,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['modern', 'current'],
    styleOfPlay: ['serve dominant', 'big forehand', 'aggressive baseliner'],
    surfaceStrengths: ['hard', 'grass'],
    shotPalette: {
      serveSpeedKmh: 240,
      forehandSpeedKmh: 135,
      signatureShots: ['first serve T on the deuce side', 'forehand short-ball put-away', 'backhand chip return'],
      weakness: 'second-serve return and movement on slow clay',
    },
    career: {
      grandSlams: 1,
      weeksAtNumberOne: 13,
      yearEndNumberOne: 1,
      careerHighRanking: 1,
      turnedPro: 2000,
      retiredYear: 2012,
    },
    bio: 'The biggest serve American tennis ever produced. Roddick won the 2003 US Open and spent the next decade defending the home patch against three of the greatest players ever. The serve was a weapon; the heart was bigger.',
    signatureMatch: 'Wimbledon 2009 Final vs Federer',
    rivalries: ['roger-federer'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'joao-fonseca',
    fullName: 'João Fonseca',
    shortName: 'Fonseca',
    tour: 'ATP',
    bornIso: '2006-08-21',
    birthplace: 'Rio de Janeiro, Brazil',
    heightCm: 188,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['aggressive baseliner', 'first-strike', 'big forehand'],
    surfaceStrengths: ['hard', 'clay'],
    shotPalette: {
      serveSpeedKmh: 210,
      forehandSpeedKmh: 140,
      signatureShots: ['forehand winner from anywhere', 'first serve out wide', 'inside-in forehand'],
    },
    career: {
      grandSlams: 0,
      careerHighRanking: 24,
      turnedPro: 2023,
    },
    bio: "Brazilian tennis hadn't had a star this exciting in a generation. Fonseca exploded into 2024 with the Next Gen Finals title, broke into the top 25 by late 2025, and arrived with a forehand that already produces ATP-tour winners. The ceiling is unwritten.",
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'arthur-fils',
    fullName: 'Arthur Fils',
    shortName: 'Fils',
    tour: 'ATP',
    bornIso: '2004-06-12',
    birthplace: 'Bondoufle, France',
    heightCm: 188,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['athletic baseliner', 'big forehand', 'first-strike'],
    surfaceStrengths: ['hard', 'clay'],
    shotPalette: {
      serveSpeedKmh: 215,
      forehandSpeedKmh: 140,
      signatureShots: ['flat forehand', 'first serve T', 'inside-out forehand'],
    },
    career: {
      grandSlams: 0,
      careerHighRanking: 14,
      turnedPro: 2021,
    },
    bio: "France's brightest hope in years. Fils brings athleticism and a willingness to play big in big moments — a forehand that flattens, a serve that bites, and the kind of confidence that suggests he expects to be top 10 sooner than later.",
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'rafael-jodar',
    fullName: 'Rafael Jódar',
    shortName: 'Jódar',
    tour: 'ATP',
    bornIso: '2006-09-17',
    birthplace: 'Spain',
    heightCm: 185,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['baseliner', 'topspin', 'breakthrough'],
    surfaceStrengths: ['clay', 'hard'],
    shotPalette: {
      signatureShots: ['heavy topspin forehand', 'rallying two-handed backhand'],
    },
    career: {
      grandSlams: 0,
      careerHighRanking: 34,
      turnedPro: 2023,
    },
    bio: "A young Spanish star of the post-Nadal generation. Jódar broke through in early 2026 — winning the Grand Prix Hassan II in Marrakech and beating Alex de Minaur in Madrid — and arrived in the top 40 before his 20th birthday. The ceiling is being written in real time.",
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'serena-williams',
    fullName: 'Serena Williams',
    shortName: 'S. Williams',
    tour: 'WTA',
    bornIso: '1981-09-26',
    birthplace: 'Saginaw, Michigan, USA',
    heightCm: 175,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['modern', 'current'],
    styleOfPlay: ['power baseliner', 'serve dominant', 'aggressive returner'],
    surfaceStrengths: ['hard', 'grass', 'clay'],
    shotPalette: {
      serveSpeedKmh: 205,
      forehandSpeedKmh: 145,
      signatureShots: ['flat first serve up the T', 'cross-court forehand', 'flat two-handed backhand winner'],
    },
    career: {
      grandSlams: 23,
      weeksAtNumberOne: 319,
      yearEndNumberOne: 5,
      careerHighRanking: 1,
      turnedPro: 1995,
      retiredYear: 2022,
    },
    bio: 'The most overpowering force the women\'s game has ever seen — and one of its most complete competitors. Twenty-three Slams, a serve that defined the era, and a will to win that turned every comeback into a coronation.',
    signatureMatch: 'Australian Open 2017 Final vs Venus',
    rivalries: ['venus-williams', 'maria-sharapova'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'steffi-graf',
    fullName: 'Steffi Graf',
    shortName: 'Graf',
    tour: 'WTA',
    bornIso: '1969-06-14',
    birthplace: 'Mannheim, West Germany',
    heightCm: 175,
    handedness: 'right',
    backhandStyle: 'one-handed',
    era: ['open-classic', 'modern'],
    styleOfPlay: ['aggressive baseliner', 'footwork', 'inside-out forehand'],
    surfaceStrengths: ['grass', 'clay', 'hard', 'carpet'],
    shotPalette: {
      serveSpeedKmh: 175,
      forehandSpeedKmh: 130,
      signatureShots: ['inside-out forehand', 'sliced one-handed backhand', 'kick serve'],
      weakness: 'high-bouncing balls to the backhand',
    },
    career: {
      grandSlams: 22,
      weeksAtNumberOne: 377,
      yearEndNumberOne: 8,
      careerHighRanking: 1,
      turnedPro: 1982,
      retiredYear: 1999,
    },
    bio: 'A backhand mostly sliced and a forehand that punished anything floating — Graf\'s economy and footwork built the only Golden Slam in tennis history (1988). 22 majors and a generation of younger players who never quite caught her.',
    signatureMatch: 'French Open 1988 Final vs Zvereva',
    rivalries: ['monica-seles', 'martina-navratilova'],
    status: 'retired',
    dataConfidence: 'verified',
  },
  {
    slug: 'aryna-sabalenka',
    fullName: 'Aryna Sabalenka',
    shortName: 'Sabalenka',
    tour: 'WTA',
    bornIso: '1998-05-05',
    birthplace: 'Minsk, Belarus',
    heightCm: 182,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['power baseliner', 'first-strike', 'big serve'],
    surfaceStrengths: ['hard', 'clay'],
    shotPalette: {
      serveSpeedKmh: 200,
      forehandSpeedKmh: 145,
      signatureShots: ['flat first serve', 'crosscourt forehand winner', 'down-the-line backhand'],
      weakness: 'serve consistency under tension',
    },
    career: {
      grandSlams: 4,
      weeksAtNumberOne: 86,
      yearEndNumberOne: 2,
      careerHighRanking: 1,
      turnedPro: 2015,
    },
    bio: 'The hardest hitter on tour and the most consistent winner on it — Sabalenka turned a sometimes-fragile serve and a fearsome forehand into four majors, back-to-back year-end #1 finishes (2024, 2025), and a sustained reign at the top. Power without compromise.',
    rivalries: ['iga-swiatek', 'coco-gauff'],
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'elena-rybakina',
    fullName: 'Elena Rybakina',
    shortName: 'Rybakina',
    tour: 'WTA',
    bornIso: '1999-06-17',
    birthplace: 'Moscow, Russia (representing Kazakhstan)',
    heightCm: 184,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['serve dominant', 'flat-hitter', 'baseliner'],
    surfaceStrengths: ['grass', 'hard'],
    shotPalette: {
      serveSpeedKmh: 200,
      forehandSpeedKmh: 140,
      signatureShots: ['first serve out wide', 'flat two-handed backhand', 'inside-out forehand'],
    },
    career: {
      grandSlams: 2,
      careerHighRanking: 2,
      turnedPro: 2017,
    },
    bio: "Six-foot serve, six-foot frame. After Wimbledon 2022 announced her, the 2026 Australian Open confirmed her — a comeback from 0-3 down in the third against Sabalenka for her second major. Few players hold serve more easily.",
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'coco-gauff',
    fullName: 'Coco Gauff',
    shortName: 'Gauff',
    tour: 'WTA',
    bornIso: '2004-03-13',
    birthplace: 'Atlanta, Georgia, USA',
    heightCm: 175,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['athletic counterpuncher', 'defense-into-offense', 'evolving forehand'],
    surfaceStrengths: ['hard', 'clay'],
    shotPalette: {
      serveSpeedKmh: 185,
      forehandSpeedKmh: 130,
      backhandSpeedKmh: 130,
      signatureShots: ['cross-court two-handed backhand', 'sliding defensive backhand', 'forehand approach'],
      weakness: 'forehand under pressure (the long-running development project)',
    },
    career: {
      grandSlams: 2,
      careerHighRanking: 2,
      turnedPro: 2018,
    },
    bio: 'Athletic, articulate, and the youngest American to win the US Open since Serena — then the 2025 French Open winner over the clay-court field, with the forehand finally arriving when it had to. The defense and footspeed were always elite; now there are two majors to match.',
    rivalries: ['iga-swiatek', 'aryna-sabalenka'],
    status: 'active',
    dataConfidence: 'verified',
  },
  {
    slug: 'iga-swiatek',
    fullName: 'Iga Świątek',
    shortName: 'Świątek',
    tour: 'WTA',
    bornIso: '2001-05-31',
    birthplace: 'Warsaw, Poland',
    heightCm: 176,
    handedness: 'right',
    backhandStyle: 'two-handed',
    era: ['current'],
    styleOfPlay: ['heavy topspin baseliner', 'clay specialist', 'aggressive returner'],
    surfaceStrengths: ['clay', 'hard'],
    shotPalette: {
      serveSpeedKmh: 175,
      forehandSpeedKmh: 130,
      forehandRpm: 3500,
      signatureShots: ['heavy topspin forehand', 'cross-court two-handed backhand', 'kick second serve'],
    },
    career: {
      grandSlams: 6,
      weeksAtNumberOne: 125,
      yearEndNumberOne: 2,
      careerHighRanking: 1,
      turnedPro: 2016,
    },
    bio: 'A clay-court genius who turned topspin into terror — six majors and a Polish flag flying high atop the WTA in the early 2020s. Świątek\'s heavy ball and unrelenting focus rewrote the women\'s game; she ceded #1 to Sabalenka in 2024 but the body of work is already historic.',
    rivalries: ['aryna-sabalenka', 'coco-gauff'],
    status: 'active',
    dataConfidence: 'verified',
  },
];
